### ISSUE TITLE
Add "#" and skip link if all files are downloaded.

### ISSUE THREAD

**Issue by ghost** [scotow/mego#1]
I am using your script with an own one and while testig mine, a folder was downloaded but the hastag was not added to the url files. Then when I try to run mego it keeps trying to download the first link even all the files have already been downloaded.

Even that, thanks for such a great script!

**Comment by scotow** [comment]
Hi, thanks for the feedback.

I updated the script to make it marks already downloaded directories as done. See commit face0ca63efed7132476abfffac029c649d87cf4 for more information.
