### ISSUE TITLE
Not creating root folder

### ISSUE THREAD

**Issue by john-arvid** [scotow/mego#4]
Not sure if it is mego or megatools. But when downloading it does not create the root folder. So I have to check each link and create a root folder for the files.

**Comment by scotow** [comment]
Just tested with this folder: https://mega.nz/folder/eGxhUZYT#-WCIha0AbCEnO7bKIl5geg.

Indeed, the root directory is not created.

Running `megatools dl` with the `--choose-files` option and choosing the top most directory will create the root directory in your current directory. But the `--choose-files` option will make megatools interactive, which is not optimal for mego.

This should be an option from megatools (or maybe the default behaviour). Anyway nothing I can do on my side.

This project really is some duck-tape over megatools, I looked in using a mega.nz library to download the files by myself, but unfortunately [go-mega](https://github.com/t3rm1n4l/go-mega) does not support public file/folder download.
