### ISSUE TITLE
Existing files downloaded before check

### ISSUE THREAD

**Issue by john-arvid** [scotow/mego#5]
Noticed that the check for an existing file is done after the download has been made.
Causes quota limit to be reached quickly.

(Sorry for all the issues, just wanted to put them out here in case they will be fixed, or for others to see if their not)

**Comment by scotow** [comment]
Are you sure about this? I just tried, and the download is not started if a file with the same name already exists.

Here is test file: https://mega.nz/file/jegnCJLK#zSFt-9rjKR6Zp7knqr_5KiMU3Fn8CKsb6A9cThD7W8c

And here is a trace:
```sh
scotow@zibo /tmp/tmp.jWf8MqrStG % mego -p 'https://mega.nz/file/jegnCJLK#zSFt-9rjKR6Zp7knqr_5KiMU3Fn8CKsb6A9cThD7W8c'
Downloaded Gillette , the best a man can get.wav
2020/06/05 01:16:46 Download of "https://mega.nz/file/jegnCJLK#zSFt-9rjKR6Zp7knqr_5KiMU3Fn8CKsb6A9cThD7W8c" done.
2020/06/05 01:16:46 All download(s) done.
scotow@zibo /tmp/tmp.jWf8MqrStG % mego -p 'https://mega.nz/file/jegnCJLK#zSFt-9rjKR6Zp7knqr_5KiMU3Fn8CKsb6A9cThD7W8c'

ERROR: Download failed for 'https://mega.nz/file/jegnCJLK#zSFt-9rjKR6Zp7knqr_5KiMU3Fn8CKsb6A9cThD7W8c': Local file already exists: ./Gillette , the best a man can get.wav
2020/06/05 01:16:48 Download of "https://mega.nz/file/jegnCJLK#zSFt-9rjKR6Zp7knqr_5KiMU3Fn8CKsb6A9cThD7W8c" done.
2020/06/05 01:16:48 All download(s) done.
```

The error in the log comes from megatools, and is interpreted normally by mego as a "this file has already been downloaded".

**Comment by john-arvid** [comment]
I had some trouble reproducing this myself, went through many different links when I noticed it, and now I can find it again. 
I saw that it was doing the percentage before it gave the file exist error.

Either way, I can't reproduce so closing this.
